// src/components/Icon.tsx
import React from 'react';
import { 
  MessageSquare, 
  Star, 
  Users, 
  BarChart3, 
  Settings, 
  Zap, 
  Shield, 
  Rocket, 
  Target, 
  Heart, 
  TrendingUp, 
  Eye, 
  Mail, 
  Phone, 
  Github, 
  Link, 
  Copy, 
  CheckCircle, 
  XCircle, 
  Clock, 
  Download, 
  Upload, 
  Globe, 
  Palette, 
  Code, 
  Database, 
  Lock, 
  Unlock, 
  Search, 
  Filter, 
  Plus, 
  Minus, 
  Edit, 
  Trash2, 
  Save, 
  RefreshCw, 
  AlertCircle, 
  Info, 
  ChevronDown, 
  ChevronUp, 
  ChevronLeft, 
  ChevronRight, 
  ArrowLeft, 
  ArrowRight, 
  ExternalLink, 
  Menu, 
  X, 
  Home, 
  User, 
  LogOut, 
  LogIn, 
  UserPlus, 
  Briefcase, 
  Award, 
  Lightbulb, 
  Smartphone, 
  Monitor, 
  Tablet, 
  Calendar, 
  MapPin, 
  DollarSign, 
  CreditCard, 
  PieChart, 
  LineChart, 
  Activity, 
  Layers, 
  Grid, 
  List, 
  Image, 
  FileText, 
  Folder,
  Share2,
  ThumbsUp,
  ThumbsDown,
  Bookmark,
  Flag,
  HelpCircle,
  PlayCircle,
  PauseCircle,
  StopCircle,
  Volume2,
  VolumeX,
  Wifi,
  WifiOff,
  Battery,
  BatteryLow,
  Sun,
  Moon,
  Coffee,
  Camera,
  Video,
  Mic,
  MicOff,
  Headphones,
  Speaker,
  Bluetooth,
  HardDrive,
  Cpu,
  Building,
  Car,
  Plane,
  Train,
  Bike,
  Bus,
  Truck,
  Ship,
  Navigation,
  Compass,
  Map,
  Route,
  Tag,
  Tags,
  Hash,
  AtSign,
  Percent,
  Euro,
  PoundSterling,
  Bitcoin,
  Banknote,
  Wallet,
  ShoppingCart,
  ShoppingBag,
  Store,
  Package,
  Gift,
  EyeOff,
  Send
} from 'lucide-react';

// Icon mapping for your app
const IconMapping = {
  // Brand/Logo
  logo: MessageSquare,
  
  // Navigation
  dashboard: BarChart3,
  testimonials: MessageSquare,
  analytics: TrendingUp,
  settings: Settings,
  home: Home,
  about: Info,
  features: Zap,
  pricing: DollarSign,
  contact: Mail,
  
  // User actions
  login: LogIn,
  logout: LogOut,
  signup: UserPlus,
  profile: User,
  user: User,
  
  // Testimonial related
  star: Star,
  rating: Star,
  review: MessageSquare,
  feedback: MessageSquare,
  approval: CheckCircle,
  rejection: XCircle,
  pending: Clock,
  
  // Widget/Display
  widget: Code,
  embed: Code,
  display: Monitor,
  preview: Eye,
  copy: Copy,
  link: Link,
  share: Share2,
  
  // Social/Contact
  email: Mail,
  phone: Phone,
  whatsapp: Smartphone,
  github: Github,
  website: Globe,
  send: Send,
  
  // Actions
  edit: Edit,
  delete: Trash2,
  save: Save,
  refresh: RefreshCw,
  search: Search,
  filter: Filter,
  add: Plus,
  remove: Minus,
  
  // Status/Alerts
  success: CheckCircle,
  error: XCircle,
  warning: AlertCircle,
  info: Info,
  loading: RefreshCw,
  
  // Business/Features
  secure: Shield,
  shield: Shield,
  fast: Zap,
  easy: Target,
  target: Target,
  growth: TrendingUp,
  customers: Users,
  insights: BarChart3,
  
  // Arrows/Navigation
  up: ChevronUp,
  down: ChevronDown,
  left: ChevronLeft,
  right: ChevronRight,
  back: ArrowLeft,
  forward: ArrowRight,
  external: ExternalLink,
  
  // Menu/Layout
  menu: Menu,
  close: X,
  grid: Grid,
  list: List,
  
  // Charts/Analytics
  chart: BarChart3,
  pieChart: PieChart,
  lineChart: LineChart,
  activity: Activity,
  
  // Time/Date
  calendar: Calendar,
  clock: Clock,
  
  // Location
  location: MapPin,
  
  // Files/Data
  file: FileText,
  folder: Folder,
  download: Download,
  upload: Upload,
  
  // Theme
  light: Sun,
  dark: Moon,
  
  // Business
  upgrade: Rocket,
  rocket: Rocket,
  pro: Award,
  award: Award,
  enterprise: Building,
  briefcase: Briefcase,
  
  // Support/Help
  help: HelpCircle,
  support: Headphones,
  
  // Collections
  collect: Target,
  form: FileText,
  
  // Performance
  speed: Zap,
  reliability: Shield,
  
  // Communication
  message: MessageSquare,
  notification: AlertCircle,
  
  // Technology
  api: Code,
  database: Database,
  
  // Security
  lock: Lock,
  unlock: Unlock,
  
  // Media
  image: Image,
  video: Video,
  
  // Interaction
  like: ThumbsUp,
  dislike: ThumbsDown,
  bookmark: Bookmark,
  flag: Flag,
  
  // Payment/Commerce
  payment: CreditCard,
  wallet: Wallet,
  cart: ShoppingCart,
  store: Store,
  package: Package,
  
  // Tools
  palette: Palette,
  layers: Layers,
  
  // Others
  verified: CheckCircle,
  unverified: XCircle,
  new: Plus,
  trending: TrendingUp,
  popular: Star,
  recommended: Award, // First occurrence - keeping this one
  
  // Additional specific icons
  admin: Shield,
  team: Users,
  stats: BarChart3,
  performance: TrendingUp,
  conversion: Target,
  engagement: Heart,
  heart: Heart,
  visibility: Eye,
  reach: Globe,
  leads: Users,
  sales: DollarSign,
  roi: TrendingUp,
  automation: Zap,
  integration: Link,
  customization: Palette,
  branding: Award,
  responsive: Monitor,
  mobile: Smartphone,
  desktop: Monitor,
  tablet: Tablet,
  snippet: Code,
  css: Palette,
  javascript: Code,
  html: Code,
  webhook: Link,
  export: Download,
  import: Upload,
  backup: Shield,
  restore: RefreshCw,
  sync: RefreshCw,
  server: Database,
  network: Wifi,
  connection: Link,
  bandwidth: Activity,
  uptime: TrendingUp,
  downtime: XCircle,
  maintenance: Settings,
  update: RefreshCw,
  version: Tag,
  tag: Tag,
  release: Rocket,
  feature: Star,
  bugfix: Zap,
  improvement: TrendingUp,
  documentation: FileText,
  guide: Info,
  tutorial: PlayCircle,
  example: Eye,
  demo: PlayCircle,
  test: CheckCircle,
  debug: Search,
  monitor: Activity,
  track: Eye,
  measure: BarChart3,
  optimize: TrendingUp,
  scale: Rocket,
  grow: TrendingUp,
  expand: Plus,
  reduce: Minus,
  focus: Target,
  goal: Flag,
  strategy: Map,
  plan: Calendar,
  schedule: Clock,
  deadline: AlertCircle,
  priority: Star,
  urgent: AlertCircle,
  important: Flag,
  optional: Info,
  required: AlertCircle,
  suggested: Lightbulb,
  lightbulb: Lightbulb,
  idea: Lightbulb,
  innovation: Rocket,
  creativity: Palette,
  design: Palette,
  development: Code,
  testing: CheckCircle,
  deployment: Rocket,
  launch: Rocket,
  announcement: Volume2,
  news: Info,
  blog: FileText,
  article: FileText,
  post: Edit,
  comment: MessageSquare,
  reply: ArrowRight,
  favorite: Heart,
  follow: Plus,
  unfollow: Minus,
  subscribe: Plus,
  unsubscribe: Minus,
  invite: UserPlus,
  referral: Share2,
  reward: Award,
  bonus: Gift,
  discount: Tag,
  coupon: Tag,
  promo: Star,
  sale: DollarSign,
  deal: Award,
  offer: Gift,
  special: Star,
  limited: Clock,
  exclusive: Award,
  premium: Star,
  free: Gift,
  trial: PlayCircle,
  beta: AlertCircle,
  alpha: AlertCircle,
  stable: CheckCircle, // First occurrence - keeping this one
  experimental: AlertCircle,
  deprecated: XCircle,
  legacy: Clock,
  modern: Star,
  latest: Rocket,
  updated: RefreshCw,
  fresh: Star,
  old: Clock,
  archived: Folder,
  deleted: Trash2,
  removed: Minus,
  hidden: EyeOff,
  visible: Eye,
  public: Globe,
  private: Lock,
  secret: Lock,
  confidential: Shield,
  encrypted: Lock,
  protected: Shield,
  safe: Shield,
  trusted: CheckCircle,
  certified: Award,
  approved: CheckCircle,
  rejected: XCircle,
  processing: RefreshCw,
  waiting: Clock,
  ready: CheckCircle,
  complete: CheckCircle,
  incomplete: Clock,
  progress: Activity,
  status: Info,
  health: Heart,
  online: CheckCircle,
  offline: XCircle,
  connected: Wifi,
  disconnected: WifiOff,
  active: CheckCircle,
  inactive: XCircle,
  enabled: CheckCircle,
  disabled: XCircle,
  on: CheckCircle,
  off: XCircle,
  yes: CheckCircle,
  no: XCircle,
  positive: ThumbsUp,
  negative: ThumbsDown,
  neutral: Minus,
  good: CheckCircle,
  bad: XCircle,
  excellent: Star,
  poor: XCircle,
  average: Minus,
  high: TrendingUp,
  low: ChevronDown,
  medium: Minus,
  maximum: TrendingUp,
  minimum: ChevronDown,
  increase: TrendingUp,
  decrease: ChevronDown,
  volatile: Activity,
  trend: TrendingUp,
  pattern: Activity,
  cycle: RefreshCw,
  loop: RefreshCw,
  repeat: RefreshCw,
  once: Plus,
  multiple: Copy,
  single: Minus,
  double: Copy,
  triple: Layers,
  many: Grid,
  few: List,
  all: Grid,
  none: X,
  some: List,
  most: BarChart3,
  least: Minus,
  more: Plus,
  less: Minus,
  equal: Minus,
  different: AlertCircle,
  same: CheckCircle,
  similar: Minus,
  unique: Star,
  common: Users,
  rare: Star,
  frequent: RefreshCw,
  occasional: Clock,
  regular: Calendar,
  irregular: AlertCircle,
  consistent: CheckCircle,
  inconsistent: AlertCircle,
  reliable: Shield,
  unreliable: AlertCircle,
  predictable: Calendar,
  unpredictable: AlertCircle,
  expected: CheckCircle,
  unexpected: AlertCircle,
  normal: CheckCircle,
  abnormal: AlertCircle,
  typical: CheckCircle,
  unusual: AlertCircle,
  standard: CheckCircle,
  custom: Settings,
  default: Minus,
  original: Star,
  modified: Edit,
  changed: Edit,
  unchanged: Minus,
  improved: TrendingUp,
  degraded: AlertCircle,
  enhanced: Star,
  compressed: Minus,
  extended: Plus,
  shortened: Minus,
  lengthened: Plus,
  widened: Plus,
  narrowed: Minus,
  enlarged: Plus,
  shrunk: Minus,
  grown: TrendingUp,
  declined: ChevronDown,
  risen: TrendingUp,
  fallen: ChevronDown,
  climbed: TrendingUp,
  dropped: ChevronDown,
  jumped: TrendingUp,
  plunged: ChevronDown,
  soared: TrendingUp,
  crashed: XCircle,
  surged: TrendingUp,
  slumped: ChevronDown,
  peaked: TrendingUp,
  bottomed: ChevronDown,
  recovered: TrendingUp,
  collapsed: XCircle,
  rebounded: TrendingUp,
  stagnated: Minus,
  accelerated: Rocket,
  decelerated: Clock,
  advanced: ArrowRight,
  retreated: ArrowLeft,
  progressed: ArrowRight,
  regressed: ArrowLeft,
  evolved: TrendingUp,
  devolved: ChevronDown,
  developed: TrendingUp,
  deteriorated: AlertCircle,
  matured: Award,
  aged: Clock,
  current: Star,
  outdated: Clock,
  recent: Star,
  ancient: Clock,
  contemporary: Star,
  historical: Clock,
  future: Rocket,
  past: ArrowLeft,
  present: Star,
  now: Star,
  then: Clock,
  when: Clock,
  where: MapPin,
  what: HelpCircle,
  why: HelpCircle,
  how: Info,
  who: User,
  which: List,
  whose: User,
  whom: User
};

// Professional Icon Component
interface IconProps {
  name: keyof typeof IconMapping;
  size?: number;
  color?: string;
  className?: string;
  style?: React.CSSProperties;
}

export const Icon: React.FC<IconProps> = ({ 
  name, 
  size = 20, 
  color = 'currentColor', 
  className = '',
  style = {} 
}) => {
  const IconComponent = IconMapping[name];
  
  if (!IconComponent) {
    console.warn(`Icon "${name}" not found`);
    return <AlertCircle size={size} color={color} className={className} style={style} />;
  }
  
  return (
    <IconComponent 
      size={size} 
      color={color} 
      className={className} 
      style={style} 
    />
  );
};

// Special styled icons for social media with brand colors
export const WhatsAppIcon: React.FC<Omit<IconProps, 'name'>> = (props) => (
  <Icon name="whatsapp" color="#25D366" {...props} />
);

export const GitHubIcon: React.FC<Omit<IconProps, 'name'>> = (props) => (
  <Icon name="github" color="#1f2937" {...props} />
);

export const EmailIcon: React.FC<Omit<IconProps, 'name'>> = (props) => (
  <Icon name="email" color="#3b82f6" {...props} />
);

// Utility function to get available icon names
export const getAvailableIcons = (): (keyof typeof IconMapping)[] => {
  return Object.keys(IconMapping) as (keyof typeof IconMapping)[];
};

// Type export for icon names
export type IconName = keyof typeof IconMapping;

export default Icon;